Matrix adding fail-fast and exclude

diff --git a/.github/workflows/matxi.yml b/.github/workflows/matxi.yml
--- a/.github/workflows/matxi.yml
+++ b/.github/workflows/matxi.yml
@@ -5,14 +5,25 @@ name: Matrix python-setup
         branches: [main]
 jobs: 
     python_setup:
-        runs-on: ubuntu-latest
-        strategy: 
-            matrix: 
+        runs-on: ${{matrix.os}}
+        strategy:
+            fail-fast: true  #if one job fails, GitHub cancels all remaining matrix jobs.
+            matrix:
+                os: [ubuntu-latest, windows-latest]
                 python-version: [3.10, 3.11, 3.12]
+                exclude:
+                    - os: windows-latest
+                      python-version: 3.10 #Exclude this combination 
+
         steps: 
           - name: pyhton-setup ${{ matrix.python-version }}
             uses: actions/setup-python@v4
             with:
               pyhton-version: ${{matrix.python-version}}
           - name: Check pyhton version
-            run: python --version
+            run: |
+              echo "Running on os ${{matrix.os}} with python ${{matrix.python-version}}"\
+              python --version
+          - name: Force failure (testing)
+            if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
+            run: exit 1
